<?php

if(function_exists("register_field_group"))
{
  register_field_group(array (
    'id' => 'acf_woo-product-extras',
    'title' => 'Propel Catalog Extras',
    'fields' => array (
      array (
        'key' => 'field_introductory_text',
        'label' => 'Introductory Text',
        'name' => 'introductory_text',
        'type' => 'wysiwyg',
        'instructions' => 'This text will display on the Course Sales. Access via [propelIntroText]',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_main_course_description',
        'label' => 'Main Course Description',
        'name' => 'main_course_description',
        'type' => 'wysiwyg',
        'instructions' => 'This text will display on the Course Sales. Access via [propelMainDescription]',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_catalog_description',
        'label' => 'Catalog Description',
        'name' => 'catalog_description',
        'type' => 'textarea',
        'instructions' => 'This will show only in the course catalog.',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_product_course_price_for_members',
        'label' => 'Price for Members',
        'name' => 'price_for_members',
        'type' => 'text',
        'instructions' => 'Use this field to display the price for members',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_product_course_more_info',
        'label' => 'Course More Info Button Label',
        'name' => 'course_more_info',
        'type' => 'text',
        'instructions' => 'Edit the Course Info button text',
        'default_value' => 'Course Info',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_product_course_authors',
        'label' => 'Course Authors',
        'name' => 'course_authors',
        'type' => 'text',
        'instructions' => 'Use this field for how the author names will display on the my courses page and the course catalog',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'propel_instructors',
        'label' => 'instructors',
        'name' => 'instructors',
        'type' => 'repeater',
        'instructions' => 'These fields will display on the individual course sales pages.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => '',
        'max' => '',
        'layout' => 'table',
        'button_label' => 'Add Row',
        'sub_fields' => array (
          array (
            'key' => 'propel_instructor_name',
            'label' => 'Instructor Name',
            'name' => 'instructor_name',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array (
            'key' => 'propel_instructor_bio',
            'label' => 'Instructor Bio',
            'name' => 'instructor_bio',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
          ),
          array (
            'key' => 'propel_instructor_image',
            'label' => 'Instructor Image',
            'name' => 'instructor_image',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
          ),
        ),
      ),
      array (
        'key' => 'field_product_credit_type',
        'label' => 'Credit Type',
        'name' => 'credit_type',
        'type' => 'text',
        'instructions' => 'Use this field for how the certificate info will display on the my courses page above the claim button',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_product_expires_in_days',
        'label' => 'Expires In (days)',
        'name' => 'course_expires_in_days',
        'type' => 'text',
        'instructions' => 'How many days does a user have access to this course?',
        'default_value' => '365',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '5',
      ),
      array (
        'key' => 'field_catalog_product_flag',
        'label' => 'Show Catalog Product Flag',
        'name' => 'show_catalog_product_flag',
        'type' => 'true_false',
        'instructions' => 'Set this field to True to show a flag on the catalog page',
        'message' => '',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_catalog_product_flag_label',
        'label' => 'Catalog Product Flag Label',
        'name' => 'catalog_product_flag_label',
        'type' => 'text',
        'instructions' => 'The label for the flag on the Catalog page',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_catalog_product_flag',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => 'update',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => 35,
      ),
      array (
        'key' => 'field_catalog_product_flag_content',
        'label' => 'Catalog Product Flag Popover Content',
        'name' => 'catalog_product_flag_popover_content',
        'type' => 'wysiwyg',
        'instructions' => 'The content for the popover when the flag is clicked',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_catalog_product_flag',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '',
        'toolbar' => 'basic',
        'media_upload' => 'no',
      ),
    ),
    'location' => array (
      array (
         array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'product',
         'order_no' => 0,
         'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'acf_after_title',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
}




