<?php
/*
Plugin Name: Pagely Cache Control
Plugin URI: http://pagely.com
Description: Disable Pagely caching on any page generated by wordpress
Version: 1.0
Author: Pagely
Author URI: http://pagely.com
License: GPL
*/

// CACHE CONTROL
if( ! defined('F_PAGELY_CACHE_CONTROL') )
   define( 'F_PAGELY_CACHE_CONTROL', TRUE); 

require_once __DIR__.'/pagely-cache-control.lib.php';

// hook to set nocache headers
add_action('wp', 'pagely_cache_control');
function pagely_cache_control()
{
    if (!is_404() && !is_user_logged_in())
    {
        global $wp;
        $cc = PagelyCacheControl::instance();
        $cc->sendNoCacheHeaders($wp);
    }
}

// process admin ui actions, needs to happen outside of the standard page handling
// because we need to set cookies, so we need to run before any random output from another
// plugin
if (isset($_POST['action']) && $_POST['action'] === 'update_pagely_cachecontrol')
{
    add_action('init', 'page_cache_control_option_post_handler');
}

function page_cache_control_option_post_handler()
{
    $cc = PagelyCacheControl::instance();
    $cc->updateConfig($_POST);
}

// admin ui
function pagely_cache_control_options()
{
    if (!pagely_role_check())
        return;

    $cc = PagelyCacheControl::instance();

    $config = $cc->config();

    include __DIR__.'/admin_html.php';
}
